global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  # cAdvisor - 컨테이너 메트릭
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # Grafana 메트릭
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # InfluxDB 메트릭
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Elasticsearch exporter (Elasticsearch 자체는 exporter가 필요)
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s

  # Claude 에이전트들 모니터링 (포트가 있다면)
  - job_name: 'claude-agents'
    static_configs:
      - targets:
        - 'claude-orchestrator:8000'
        - 'tmux-claude-analyzer-1:8001'
        - 'tmux-claude-executor-1:8002'
        - 'tmux-claude-researcher-1:8003'
    metrics_path: '/metrics'
    scrape_interval: 30s
    honor_labels: true