apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: fortinet
  labels:
    app: fortinet
    component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortinet
      component: cache
  template:
    metadata:
      labels:
        app: fortinet
        component: cache
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        command:
        - redis-server
        - --appendonly
        - "yes"
        - --maxmemory
        - "256mb"
        - --maxmemory-policy
        - "allkeys-lru"
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-pvc