name: Bug Report
description: Create a report to help us improve the FortiGate Nextrade platform
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thank you for reporting a bug! Please fill out the form below to help us understand and reproduce the issue.
        
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - FortiGate API Client
        - FortiManager Integration
        - Web Interface
        - Authentication System
        - Database/Redis
        - Docker Container
        - CI/CD Pipeline
        - MSA Services
        - Packet Sniffer
        - ITSM Integration
        - Other
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      placeholder: "v1.3.0"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead
    validations:
      required: true
      
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      options:
        - Development (Local)
        - Docker Container
        - Kubernetes
        - Production
        - MSA Mode
        - Offline Mode
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error logs
      placeholder: |
        ```
        Error logs here...
        ```
        
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues
        - label: I have provided all required information
        - label: I can reproduce this issue consistently