name: Feature Request
description: Suggest a new feature or enhancement for the FortiGate Nextrade platform
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Thank you for suggesting a new feature! Please describe your idea in detail.
        
  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area would this feature affect?
      options:
        - FortiGate Integration
        - FortiManager Hub
        - Web Interface
        - API Enhancement
        - Security Features
        - Monitoring & Analytics
        - MSA Services
        - CI/CD Pipeline
        - Documentation
        - Performance
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the current limitation?
      placeholder: Describe the problem or limitation this feature would address
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature in practice
      placeholder: Provide specific examples of how this feature would be used
    validations:
      required: true
      
  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: What type of user would benefit from this feature?
      multiple: true
      options:
        - System Administrator
        - Security Analyst
        - Network Engineer
        - Developer
        - End User
        - API Consumer
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete and ready for use?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
        
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing feature requests
        - label: I have provided a clear use case
        - label: This feature aligns with the project's goals