#!/bin/bash
# Cleanup script for unused resources
# Generated by cleanup-unused-resources.py

echo "Starting cleanup..."
FREED=0

# Clean Python cache
echo "Cleaning Python cache..."
find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null
find . -type f -name "*.pyc" -delete 2>/dev/null
find . -type f -name "*.pyo" -delete 2>/dev/null

# Clean test artifacts
echo "Cleaning test artifacts..."
rm -rf .pytest_cache/
rm -rf htmlcov/
rm -f .coverage
rm -f coverage.xml

# Clean temporary files
echo "Cleaning temporary files..."
find . -type f -name "*.tmp" -delete 2>/dev/null
find . -type f -name "*.temp" -delete 2>/dev/null
find . -type f -name "*.bak" -delete 2>/dev/null
find . -type f -name "*.swp" -delete 2>/dev/null
find . -type f -name "*~" -delete 2>/dev/null

# Clean build artifacts
echo "Cleaning build artifacts..."
rm -rf build/
rm -rf dist/
rm -rf *.egg-info/

# Clean IDE files
echo "Cleaning IDE files..."
rm -rf .idea/
rm -rf .vscode/
rm -f .DS_Store

# Clean security scan reports
echo "Cleaning old scan reports..."
rm -f bandit_report.json
rm -f bandit-report.json

# Clean old logs (keep last 7 days)
echo "Cleaning old logs..."
find logs/ -type f -name "*.log" -mtime +7 -delete 2>/dev/null

# Clean Docker (optional)
echo ""
echo "Docker cleanup (optional - requires confirmation):"
echo "  docker system prune -f"
echo "  docker volume prune -f"

# Report
echo ""
echo "Cleanup completed!"
du -sh .
