name: Deploy to Cloudflare

on:
  push:
    branches: [main, master, develop]
    paths:
      - 'src/**'
      - 'wrangler.toml'
      - 'requirements.txt'
      - '.github/workflows/cloudflare-deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g wrangler

      - name: Deploy to Cloudflare
        run: |
          if [ "${{ github.event.inputs.environment }}" = "staging" ]; then
            wrangler deploy --env staging
          else
            wrangler deploy --env production
          fi

      - name: Deployment summary
        if: always()
        run: |
          echo "## 🚀 Cloudflare Deployment" >> $GITHUB_STEP_SUMMARY
          echo "**Environment:** ${{ github.event.inputs.environment || 'production' }}" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
